fix: [select-dialog] select dialog name filter format item show error
linuxdeepin/dde-file-manager pull request #1075
Opened 2023-06-02 07:39 UTC by GongHeng2017

1. remove useless code of name filter function
2. add logic code of after set namefilter, immediately refresh
3. when set SingleSelection, should not support multiple choices

Log: fix issue
Bug: https://pms.uniontech.com/bug-view-197323.html

2023-06-05 08:52 UTC, Clauszy requested changes

2023-06-05 08:52 UTC, Clauszy commented on src/plugins/filemanager/core/dfmplugin-workspace/models/fileitemdata.h
> +    void setAvailableState(bool b);
setAvailable

2023-06-05 08:52 UTC, Clauszy commented on src/plugins/filemanager/core/dfmplugin-workspace/models/fileitemdata.h
> +    bool isAvailable { true };
available

2023-06-05 09:58 UTC, Clauszy submitted a review, later dismissed

2023-06-05 10:07 UTC, liyigang1 approved these changes

2023-06-05 10:15 UTC, Lighto-Ku approved these changes

2023-06-05 10:16 UTC, GongHeng2017 commented
/merge

2023-06-09 06:46 UTC, GongHeng2017 commented
/merge

2023-06-09 06:48 UTC, GongHeng2017 commented
/merge

2023-06-09 07:06 UTC, GongHeng2017 commented
/merge

2023-06-09 10:02 UTC, max-lvs approved these changes

2023-06-09 10:02 UTC, GongHeng2017 commented
/merge

2023-06-09 10:03 UTC, merged