feat: [menu]Remove parameters passed out using fileinfo from the right-click menu bar
linuxdeepin/dde-file-manager pull request #1101
Opened 2023-06-10 08:40 UTC by liyigang1

1. Open the local file information cache. 2. Add a mandatory creation fileinfo replacement caching mechanism. 3. Remove the focusfileinfo parameter passed out from the menu. 4. Modify the selectfileinfos parameter QList<FileInfoPointer>to the createdfileinfoUrls parameter QList<QUrl>. 5. Modify the use of createdfileinfoUrls in all menuscenes.

Log: Remove parameters passed out using fileinfo from the right-click menu bar

2023-06-12 01:28 UTC, Clauszy requested changes
selectCreatedInfoUrls 会为菜单带来不确定性，出现某个菜单项一会儿有，一会儿没有的问题

2023-06-12 01:50 UTC, liyigang1 commented
> selectCreatedInfoUrls 会为菜单带来不确定性，出现某个菜单项一会儿有，一会儿没有的问题

和军哥讨论只是用焦点fileinfo

2023-06-12 03:24 UTC, liyigang1 commented
> selectCreatedInfoUrls 会为菜单带来不确定性，出现某个菜单项一会儿有，一会儿没有的问题

还原到以前的使用方式，不做修改，后面在考虑怎么去优化鼠标右键的问题

2023-06-13 01:52 UTC, Johnson-zs commented on include/dfm-base/base/schemefactory.h
> +        if (type == Global::CreateFileInfoType::kCreateFileInfoRePlaceCache)
Replace

2023-06-13 01:54 UTC, Johnson-zs commented on src/plugins/common/core/dfmplugin-bookmark/menu/bookmarkmenuscene.cpp
> +    d->focusFile = d->selectFiles.first();
有判空检查么

2023-06-13 02:02 UTC, Johnson-zs commented on include/dfm-base/dfm_global_defines.h
> +    kCreateFileInfoRePlaceCache = 5    // create file info replace cache file info
1. 这个机制意义不清晰
2. 这个机制和右键菜单无任何关系，建议拆分提交

2023-06-13 02:15 UTC, itsXuSt requested changes

2023-06-13 02:15 UTC, itsXuSt commented on src/plugins/common/core/dfmplugin-menu/extendmenuscene/extendmenuscene.cpp
> +               qDebug() << errString;
需要些表意更清晰的日志记录，后面一样。

2023-06-13 02:15 UTC, itsXuSt commented on src/plugins/common/core/dfmplugin-menu/menuscene/sharemenuscene.cpp
> +        if (f->isAttributes(OptInfoType::kIsDir)) {
create 函数可能返空。

2023-06-13 02:15 UTC, itsXuSt commented on src/plugins/filemanager/core/dfmplugin-workspace/models/rootinfo.cpp
> +QString RootInfo::currentKey(const QString &sendptr)
变量名 ptr 但是是个引用。

2023-06-13 02:15 UTC, itsXuSt commented on src/plugins/filemanager/core/dfmplugin-workspace/utils/traversaldirthreadmanager.cpp
> +    key = QString::number(quintptr(this), 16);
意思是记录一个 token 以便信号可以被发起改操作的对象标识到？

2023-06-13 02:15 UTC, itsXuSt commented on src/plugins/filemanager/core/dfmplugin-workspace/utils/traversaldirthreadmanager.h
> +    QString key;
如果是上述那样的表意的话，变量名需要修改，或者把注释写清楚。例如 operateToken 之类的。

2023-06-13 02:15 UTC, itsXuSt commented on src/plugins/filemanager/dfmplugin-avfsbrowser/menu/avfsmenuscene.cpp
> +        d->focusFileInfo = InfoFactory::create<FileInfo>(d->selectFiles.first());
判空。下同。

2023-06-13 02:26 UTC, Johnson-zs commented on src/plugins/common/dfmplugin-dirshare/dirsharemenu/dirsharemenuscene.cpp
> +    d->focusFileInfo = InfoFactory::create<FileInfo>(u);
自查，检查空指针

2023-06-13 03:34 UTC, max-lvs approved these changes

2023-06-13 03:35 UTC, liyigang1 commented
/merge

2023-06-13 03:37 UTC, max-lvs approved these changes

2023-06-13 03:41 UTC, Lighto-Ku approved these changes

2023-06-13 03:43 UTC, Clauszy approved these changes

2023-06-13 03:45 UTC, itsXuSt approved these changes

2023-06-13 06:45 UTC, closed without merging