feat: thumbnail optimization
linuxdeepin/dde-file-manager pull request #1149
Opened 2023-06-25 05:38 UTC by Kakueeen

1.Generate thumbnails in an asynchronous thread
2.Logic is separated from FileInfo

Log: thumbnail optimization
Task: https://pms.uniontech.com/task-view-272315.html

2023-06-25 07:22 UTC, Lighto-Ku commented on src/plugins/filemanager/core/dfmplugin-workspace/models/fileviewmodel.cpp
> +        info->refresh();
这里为啥要调refresh

2023-06-25 07:22 UTC, Lighto-Ku commented on src/dfm-base/utils/thumbnail/thumbnailfactory.cpp
> +    }
这个判断放回主线程会不会有性能问题，测一下视图大量图片文件滚动会不会卡顿

2023-06-25 09:57 UTC, itsXuSt requested changes

2023-06-25 09:57 UTC, itsXuSt commented on src/dfm-base/utils/thumbnail/thumbnailhelper.cpp
> +    if (!checkThumbEnable(url))
放到最前面，在缩略图关闭的场景下能避免创建 FileInfo

2023-06-25 09:57 UTC, itsXuSt commented on src/dfm-base/utils/thumbnail/thumbnailfactory.cpp
> +    }
这个是在子线程里跑的缩略图生成函数，另一个同名函数是 enqueue 函数。确实应该修改函数名称加以区分。

2023-06-25 09:57 UTC, itsXuSt commented on src/dfm-base/utils/thumbnail/thumbnailfactory.cpp
> +QImage ThumbnailFactory::createThumbnail(const QUrl &url, ThumbnialSize size)
换个函数名跟私有函数区分下比较好，比如 requestThumbIcon?

2023-06-25 09:57 UTC, itsXuSt commented on src/dfm-base/utils/thumbnail/thumbnailfactory.cpp
> +    if (d->creators.contains(mimeType))
可以加个打印。

2023-06-25 10:06 UTC, Kakueeen commented on src/plugins/filemanager/core/dfmplugin-workspace/models/fileviewmodel.cpp
> +        info->refresh();
将 fileInfo 中的 loadingThumbnail 设为false，让其重新去获取缩略图

2023-06-25 10:06 UTC, Kakueeen commented on src/dfm-base/utils/thumbnail/thumbnailhelper.cpp
> +    if (!checkThumbEnable(url))
ok

2023-06-25 10:06 UTC, Kakueeen commented on src/dfm-base/utils/thumbnail/thumbnailfactory.cpp
> +    if (d->creators.contains(mimeType))
ok

2023-06-25 10:06 UTC, Kakueeen commented on src/dfm-base/utils/thumbnail/thumbnailfactory.cpp
> +QImage ThumbnailFactory::createThumbnail(const QUrl &url, ThumbnialSize size)
ok

2023-06-25 10:06 UTC, Kakueeen commented on src/dfm-base/utils/thumbnail/thumbnailfactory.cpp
> +    }
判断是在线程中，后面接口换个名字

2023-06-26 08:22 UTC, Lighto-Ku approved these changes

2023-06-27 02:21 UTC, itsXuSt approved these changes

2023-06-28 02:03 UTC, max-lvs approved these changes

2023-06-28 02:20 UTC, merged