fix: [background] Unable to obtain the correct wallpaper in multi Wor…
linuxdeepin/dde-file-manager pull request #1193
Opened 2023-07-10 09:02 UTC by LiHua000

…kspace after reboot.

Log: When starting the desktop, read the configuration file to obtain the correct workspace.

Bug: https://pms.uniontech.com/bug-view-197559.html

2023-07-10 09:15 UTC, Clauszy requested changes

2023-07-10 09:15 UTC, Clauszy commented on src/plugins/desktop/ddplugin-background/backgroundservice.cpp
> +    if (ddeFile.open(QIODevice::ReadOnly | QIODevice::Text)) {
ddefile?换个名字吧

2023-07-10 09:15 UTC, Clauszy commented on src/plugins/desktop/ddplugin-background/backgroundservice.cpp
> +                currentWorkspaceIndex = line.mid(QString("CurrentDesktop=").length()).toInt();
get接口不应该直接复制
currentWorkspaceIndex=getCurrentWorkspaceIndex()

2023-07-10 09:15 UTC, Clauszy commented on src/plugins/desktop/ddplugin-background/backgroundservice.cpp
> +                currentWorkspaceIndex = line.mid(QString("CurrentDesktop=").length()).toInt();
缺失必要的错误处理，读出的值为异常，或没有这个字段等

2023-07-10 09:15 UTC, Clauszy commented on src/plugins/desktop/ddplugin-background/backgroundservice.cpp
> +                currentWorkspaceIndex = line.mid(QString("CurrentDesktop=").length()).toInt();
mid之后加个QString::trimmed()去掉尾部符号

2023-07-10 09:24 UTC, itsXuSt requested changes

2023-07-10 09:24 UTC, itsXuSt commented on src/plugins/desktop/ddplugin-background/backgroundservice.cpp
> +void BackgroundService::getCurrentWorkspaceIndex()
函数名与返回值不匹配。建议根据函数实际用途调整函数名。
根据用途来看，似乎叫 init...Index 更合适。
或者将 index 返回，在调用处赋值。

2023-07-10 09:25 UTC, itsXuSt commented on src/plugins/desktop/ddplugin-background/backgroundservice.cpp
> +                currentWorkspaceIndex = line.mid(QString("CurrentDesktop=").length()).toInt();
这个文件格式可以直接用 QSetting 解析。

2023-07-10 09:28 UTC, itsXuSt commented on src/plugins/desktop/ddplugin-background/backgroundservice.cpp
> +                currentWorkspaceIndex = line.mid(QString("CurrentDesktop=").length()).toInt();
QSettings::value("Workspace/CurrentDesktop", -1).toInt()

2023-07-11 08:06 UTC, Clauszy commented on src/plugins/desktop/ddplugin-background/backgroundservice.cpp
> +    if (!ok) {
!ok || currentidx < 1

2023-07-11 08:08 UTC, Clauszy commented on src/plugins/desktop/ddplugin-background/backgroundservice.cpp
> +    int currentIdx = settings.value("Workspace/CurrentDesktop").toInt(&ok);
加个默认值1

2023-07-11 08:19 UTC, Clauszy approved these changes

2023-07-11 09:29 UTC, LiHua000 commented
/merge

2023-07-11 09:29 UTC, merged