fix: [property-dialog] the device name show error.
linuxdeepin/dde-file-manager pull request #1353
Opened 2023-08-16 12:58 UTC by GongHeng2017

1. the devece name show error in device property dialog, and fix it.
2. adjust the UI

Log: fix issue
Bug: https://pms.uniontech.com/bug-view-214867.html

2023-08-17 01:19 UTC, max-lvs submitted a review, later dismissed

2023-08-18 02:04 UTC, itsXuSt requested changes

2023-08-18 02:04 UTC, itsXuSt commented on src/plugins/filemanager/core/dfmplugin-computer/dfmplugin_computer_global.h
> +    QString fileBaseName;
deviceDesc // 设备描述符

2023-08-18 02:04 UTC, itsXuSt commented on src/plugins/filemanager/core/dfmplugin-computer/utils/computerutils.cpp
> +    devInfo.fileBaseName = info->baseName();
baseName 的转换过于隐匿。直接使用 extraProperty 获取 kDevice 属性。

2023-08-18 02:33 UTC, GongHeng2017 commented on src/plugins/filemanager/core/dfmplugin-computer/utils/computerutils.cpp
> +    devInfo.fileBaseName = info->baseName();
done

2023-08-18 02:33 UTC, GongHeng2017 commented on src/plugins/filemanager/core/dfmplugin-computer/dfmplugin_computer_global.h
> +    QString fileBaseName;
done

2023-08-18 02:39 UTC, itsXuSt approved these changes

2023-08-18 03:37 UTC, max-lvs approved these changes

2023-08-18 03:37 UTC, merged