test: [UT]add ut and at
linuxdeepin/dde-file-manager pull request #1384
Opened 2023-08-24 01:49 UTC by scx005548

add desktop-background ut ,desktop-wallpapersetting ut ,desktop-organizer ut , desktop-core ut and desktop-canvas ut add titlebar at and workspace at

Log: as des
Task: https://pms.uniontech.com/task-view-278229.html

2023-08-25 02:15 UTC, Clauszy requested changes

2023-08-25 02:15 UTC, Clauszy commented on src/plugins/desktop/core/ddplugin-canvas/view/operator/fileoperatorproxy.cpp
> +
无效提交

2023-08-25 02:15 UTC, Clauszy commented on src/plugins/desktop/core/ddplugin-canvas/watermask/deepinlicensehelper.cpp
> +        qInfo() << "no  such property: ServiceProperty in license";
无意义的提交

2023-08-25 02:15 UTC, Clauszy commented on src/plugins/filemanager/core/dfmplugin-titlebar/dfmplugin_titlebar_global.h
> +inline constexpr char kAcComputerTitleBarTheAddBtn[] { "theAdd_button" };
the？

2023-08-25 02:15 UTC, Clauszy commented on src/plugins/filemanager/core/dfmplugin-workspace/views/workspacewidget.cpp
> +
同

2023-08-25 02:15 UTC, Clauszy commented on tests/all-ut-prj-running.sh
> +
同

2023-08-25 02:19 UTC, Kakueeen commented on tests/plugins/desktop/core/ddplugin-canvas/broker/ut_canvasgridbroker.cpp
> +   QPoint *pos = new QPoint(1,1);
这里会有内存泄漏

2023-08-25 02:19 UTC, Kakueeen commented on tests/plugins/desktop/core/ddplugin-canvas/broker/ut_canvasgridbroker.cpp
> +    QPoint *pos = new QPoint(1,1);
同上

2023-08-25 02:19 UTC, Kakueeen commented on tests/plugins/desktop/core/ddplugin-canvas/broker/ut_canvasmodelbroker.cpp
> +    CanvasModelBroker *broker = new CanvasModelBroker(proxy);
同上

2023-08-25 02:19 UTC, Kakueeen commented on tests/plugins/desktop/core/ddplugin-canvas/broker/ut_fileinfomodelbroker.cpp
> +    QModelIndex *index = new QModelIndex(1,1,nullptr,nullptr);
同上

2023-08-25 02:19 UTC, Kakueeen commented on tests/plugins/desktop/core/ddplugin-canvas/delegate/ut_itemeditor.cpp
> +    event->k = Qt::Key_Backtab;
同上

2023-08-25 02:19 UTC, Kakueeen commented on tests/plugins/desktop/core/ddplugin-canvas/delegate/ut_itemeditor.cpp
> +    QFocusEvent *event = new QFocusEvent(QEvent::FocusIn);
同上

2023-08-29 05:52 UTC, max-lvs commented on src/plugins/filemanager/core/dfmplugin-titlebar/dfmplugin_titlebar_global.h
> +
多余的空格

2023-08-29 05:52 UTC, max-lvs commented on src/plugins/filemanager/core/dfmplugin-titlebar/dialogs/connecttoserverdialog.cpp
> +
格式问题

2023-08-29 05:52 UTC, max-lvs commented on tests/plugins/desktop/core/ddplugin-canvas/CMakeLists.txt
> +
格式问题

2023-08-30 08:53 UTC, scx005548 commented
/merge

2023-08-30 08:55 UTC, scx005548 commented
\merge

2023-08-30 09:03 UTC, scx005548 commented
/merge

2023-08-31 02:00 UTC, Clauszy requested changes

2023-08-31 02:00 UTC, Clauszy commented on tests/plugins/desktop/ddplugin-wallpapersetting/private/ut_autoactivatewindow.cpp
> +        aa = new AutoActivateWindowPrivate(window);
AutoActivateWindowPrivate 类可以直接用AutoActivateWindow的d，而不是新new一个

2023-08-31 02:14 UTC, scx005548 commented on tests/plugins/desktop/ddplugin-wallpapersetting/private/ut_autoactivatewindow.cpp
> +        aa = new AutoActivateWindowPrivate(window);
已修改

2023-08-31 02:20 UTC, Clauszy approved these changes

2023-08-31 02:23 UTC, scx005548 commented
/merge

2023-08-31 03:04 UTC, scx005548 commented
/merge

2023-08-31 03:04 UTC, merged