fix: [vault] the old vault not mv the new path
linuxdeepin/dde-file-manager pull request #1387
Opened 2023-08-24 07:38 UTC by GongHeng2017

move the old path to new vault path

Log: fix issue
Bug: https://pms.uniontech.com/bug-view-215789.html

2023-08-24 08:00 UTC, Clauszy requested changes

2023-08-24 08:00 UTC, Clauszy commented on src/plugins/filemanager/dfmplugin-vault/views/removevaultview/vaultremoveprogressview.cpp
>                          QFile::remove(kVaultBasePath + QDir::separator() + kVaultConfigFileName);
删文件为高风险操作，需加info日志

2023-08-24 08:00 UTC, Clauszy commented on src/tools/upgrade/units/vaultupgradeunit.cpp
> +    if (!dir.rename(encryptDirPathOld, encryptDirPathNew))
同样加日志

2023-08-24 08:08 UTC, GongHeng2017 commented on src/plugins/filemanager/dfmplugin-vault/views/removevaultview/vaultremoveprogressview.cpp
>                          QFile::remove(kVaultBasePath + QDir::separator() + kVaultConfigFileName);
done

2023-08-24 08:14 UTC, GongHeng2017 commented on src/tools/upgrade/units/vaultupgradeunit.cpp
> +    if (!dir.rename(encryptDirPathOld, encryptDirPathNew))
done

2023-08-24 08:37 UTC, Kakueeen commented on src/tools/upgrade/units/vaultupgradeunit.cpp
> +    return false;
return isNeedUpgrade() ?

2023-08-24 08:37 UTC, Kakueeen commented on src/tools/upgrade/units/vaultupgradeunit.cpp
> +        return false;
这些提示信息看上去是给用户看的，但是用户看不到

2023-08-24 08:37 UTC, Kakueeen commented on src/tools/upgrade/units/vaultupgradeunit.cpp
> +    return false;
return QFile::exists(cryfsConfigFilePathOld) && !QFile::exists(cryfsConfigFilePathNew)

2023-08-24 08:37 UTC, Kakueeen commented on src/tools/upgrade/units/vaultupgradeunit.cpp
> +    cryfsConfigFilePathNew = kVaultBasePath + QDir::separator() + QString(kVaultEncrypyDirName) + QDir::separator() + QString(kCryfsConfigFileName);
cppcheck 警告

2023-08-24 09:19 UTC, GongHeng2017 commented on src/tools/upgrade/units/vaultupgradeunit.cpp
> +        return false;
日志能看到就行

2023-08-24 09:20 UTC, GongHeng2017 commented on src/tools/upgrade/units/vaultupgradeunit.cpp
> +        return false;
正常用户操作不会进入这种错误状态

2023-08-24 09:40 UTC, Kakueeen approved these changes

2023-08-25 07:09 UTC, Kakueeen approved these changes

2023-08-25 08:35 UTC, Johnson-zs commented on src/tools/upgrade/units/vaultupgradeunit.h
> +static constexpr char kVaultDecryptDirName[] { "vault_unlocked" };
这里没改？

2023-08-25 08:39 UTC, GongHeng2017 commented on src/tools/upgrade/units/vaultupgradeunit.h
> +static constexpr char kVaultDecryptDirName[] { "vault_unlocked" };
done

2023-08-25 08:42 UTC, Johnson-zs approved these changes

2023-08-25 09:19 UTC, Clauszy approved these changes

2023-08-25 09:36 UTC, GongHeng2017 commented
/merge

2023-08-25 09:36 UTC, merged