fix: never treat mobile device as Data Disk.
linuxdeepin/dde-file-manager pull request #1419
Opened 2023-09-09 04:44 UTC by hotime

增加判断条件，当挂载点不以"/media/"开头时，分区卷标以"_dde_data"开头的分区才会被显示为数据分区。
以避免移动设备中分卷卷标以"_dde_data"开头的分区被显示为数据分区，造成难以区分外置磁盘和内置磁盘的情况。
[论坛反馈](https://bbs.deepin.org/post/262009)

2023-09-11 05:37 UTC, itsXuSt requested changes

2023-09-11 05:37 UTC, itsXuSt commented on src/dfm-base/base/device/deviceutils.cpp
> +    if (moutPoint == "/")
修改下拼写。mountPoint

2023-09-11 07:42 UTC, hotime commented on src/dfm-base/base/device/deviceutils.cpp
> +    if (moutPoint == "/")
已改正拼写，感谢指正。

2023-09-12 01:56 UTC, max-lvs approved these changes

2023-09-12 01:57 UTC, max-lvs commented on src/dfm-base/base/device/deviceutils.cpp
> +    if (moutPoint == "/")
感谢，方案review 已经通过，可以提交了

2023-09-12 09:06 UTC, itsXuSt approved these changes
使用 /merge 指令合并代码。

2023-09-12 11:07 UTC, hotime commented
/merge

2023-09-12 11:07 UTC, merged