右键菜单支持反选操作
linuxdeepin/dde-file-manager pull request #1425
Opened 2023-09-12 02:15 UTC by itsXuSt

as title.

Log: Now you can reverse select your files.

Task: https://pms.uniontech.com/task-view-292113.html

2023-09-12 07:07 UTC, Lighto-Ku approved these changes

2023-09-12 09:29 UTC, Clauszy requested changes

2023-09-12 09:29 UTC, Clauszy commented on src/plugins/common/core/dfmplugin-menu/menuscene/opendirmenuscene.cpp
> +    // invert select all
select all?

2023-09-12 09:29 UTC, Clauszy commented on src/plugins/common/core/dfmplugin-menu/menuscene/opendirmenuscene.cpp
> +        dpfSlotChannel->push("dfmplugin_workspace", "slot_View_ReverseSelect", d->windowId);
公共插件发这个不好吧。
这里可以不实现这个action，直接返回false。然后在桌面和文管的菜单中拦截并实现
参考kOpenDirMenuSceneName kClipBoardMenuSceneName那些

2023-09-12 09:39 UTC, Clauszy approved these changes

2023-09-13 06:19 UTC, itsXuSt commented
/merge

2023-09-13 06:19 UTC, merged