fix: [ddailog] fix ddailog modal bug in wayland
linuxdeepin/dde-file-manager pull request #1475
Opened 2023-10-08 06:53 UTC by pppanghu77

Under wayland, it is necessary to set a parent class to indicate the hierarchical relationship of the window

Log: fix ddailog modal bug in wayland
Bug: https://pms.uniontech.com/bug-view-201353.html

2023-10-08 09:39 UTC, itsXuSt requested changes
测试下 x11 下给 DDialog 设置父对象后是否影响其他窗口的正常操作。（在 DDialog 没退出之前）

2023-10-08 09:49 UTC, pppanghu77 commented
> 测试下 x11 下给 DDialog 设置父对象后是否影响其他窗口的正常操作。（在 DDialog 没退出之前）
x11下没有设置父类

2023-10-08 09:50 UTC, itsXuSt approved these changes

2023-10-08 09:55 UTC, Johnson-zs approved these changes

2023-10-08 09:57 UTC, liyigang1 approved these changes

2023-10-09 02:46 UTC, pppanghu77 commented
/merge

2023-10-09 02:46 UTC, merged