feat: Network Neighborhood feature blocking
linuxdeepin/dde-file-manager pull request #1508
Opened 2023-10-20 03:28 UTC by liyigang1

Block shortcuts delete and shift+delete in Network Neighborhood, mount and properties in menu, and block space previews

Log: Network Neighborhood feature blocking
Task: https://pms.uniontech.com/task-view-297613.html

2023-10-20 06:33 UTC, itsXuSt requested changes
插件内部业务应该通过 hook 去解决，不能在 workspace 里加插件的 url 判定。

2023-10-20 06:56 UTC, liyigang1 commented
> 插件内部业务应该通过 hook 去解决，不能在 workspace 里加插件的 url 判定。

好的，离开去修改

2023-10-23 05:25 UTC, max-lvs approved these changes

2023-10-23 05:28 UTC, liyigang1 commented
/merge

2023-10-23 05:28 UTC, merged