feat: [report]report log
linuxdeepin/dde-file-manager pull request #1560
Opened 2023-11-10 07:39 UTC by Lighto-Ku

report some config log when app startup

Log: add report log
Task: https://pms.uniontech.com/task-view-292795.html

2023-11-10 10:01 UTC, max-lvs submitted a review, later dismissed

2023-11-10 10:03 UTC, Clauszy requested changes

2023-11-10 10:03 UTC, Clauszy commented on src/plugins/desktop/ddplugin-background/backgroundplugin.cpp
> +    dpfSlotChannel->connect("ddplugin_background", "slot_FetchUseColorBackgorund", backgroundManager, &BackgroundManager::useColorBackground);
slot_FetchUseColorBackgorund
单词background

2023-11-10 10:16 UTC, Clauszy approved these changes

2023-11-13 01:22 UTC, Lighto-Ku commented
/merge

2023-11-13 01:53 UTC, Lighto-Ku commented
/merge

2023-11-13 01:53 UTC, merged