fix: Drag a large file to the system disk, but there is no prompt indicating insufficient disk space. The file manager crashes directly
linuxdeepin/dde-file-manager pull request #1620
Opened 2023-12-11 08:16 UTC by liyigang1

Check the disk space usage using the Gio interface. The space provided by Gio is sufficient, but in reality, it is not enough. Copying large files also uses mmap, so there will be no errors and crashes directly. Modify the unified device to obtain free space on the device

Log: Drag a large file to the system disk, but there is no prompt indicating insufficient disk space. The file manager crashes directly
Bug: https://pms.uniontech.com/bug-view-233019.html

2023-12-12 02:06 UTC, itsXuSt requested changes

2023-12-12 02:06 UTC, itsXuSt commented on src/dfm-base/base/device/deviceproxymanager.cpp
> +    d->initMounts();
如果能确认是查询块设备，则可以通过 QStorageInfo::device 函数拿到当前路径对应的块设备节点 /dev/xxx ，再通过 DBlockDeviceMonitor 中的 resolveDeviceNode 可以获取到 ID，然后再查该 ID 对应的设备信息。
避免全量遍历。

2023-12-12 02:43 UTC, liyigang1 commented on src/dfm-base/base/device/deviceproxymanager.cpp
> +    d->initMounts();
这里不止查询块设备的剩余还有查询协议设备的，所以才去遍历所有，使用StorageInfo::device会卡顿

2023-12-14 05:19 UTC, max-lvs approved these changes, later dismissed

2023-12-14 06:24 UTC, max-lvs approved these changes

2023-12-14 06:45 UTC, merged