feat(pro): able to disable desktop shortcut and context menu
linuxdeepin/dde-file-manager pull request #163
Opened 2019-05-10 08:59 UTC by BLumia

``` json
$ cat ~/.config/deepin/dde-file-manager.obtusely.json 
{
	"ApplicationAttribute": {
		"DisableDesktopContextMenu": true,
		"DisableDesktopShortcuts": true
	}
}
```

如上配置时，右键菜单是完全禁掉了，快捷键是例外了上下左右回车，以及小键盘上的上下左右回车，其他都禁掉了。

2019-05-10 09:23 UTC, zccrs requested changes

2019-05-10 09:23 UTC, zccrs commented on dde-desktop/view/canvasgridview.cpp
> +    if (Q_UNLIKELY(DFMApplication::genericObtuselySetting()->value("ApplicationAttribute", "DisableDesktopContextMenu", false).toBool())) {
使用 appObtuselySetting

2019-05-10 11:49 UTC, hualet approved these changes

2019-05-14 03:53 UTC, zccrs approved these changes

2019-05-14 05:09 UTC, merged