fix: [property-dialog] the icon show error
linuxdeepin/dde-file-manager pull request #1648
Opened 2023-12-21 08:28 UTC by GongHeng2017

1. the symlink picture show error
2. do not set the redirected url.

Log: fix issue
Bug: https://pms.uniontech.com/bug-view-235661.html

2023-12-21 08:47 UTC, max-lvs approved these changes

2023-12-21 09:48 UTC, liyigang1 requested changes

2023-12-21 09:48 UTC, liyigang1 commented on src/plugins/common/core/dfmplugin-propertydialog/views/filepropertydialog.cpp
> +        QUrl localUrl = fileInfo->urlOf(FileInfo::FileUrlInfoType::kUrl);
这么修改有问题，这里是要使用准确的真实路径去读去文件的缩略图，如果是链接文件读取不到，先判断文件是否可以重定向，在去读取重定向

2023-12-22 06:54 UTC, liyigang1 approved these changes

2023-12-22 06:55 UTC, GongHeng2017 commented
/merge

2023-12-22 06:55 UTC, merged