chore: [dconfig]install view config
linuxdeepin/dde-file-manager pull request #1718
Opened 2024-01-10 03:11 UTC by Lighto-Ku

install new config file of view to dconfig dir.

Log: install view config

2024-01-11 05:26 UTC, itsXuSt requested changes
配置json文件没加进来

2024-01-12 01:12 UTC, GongHeng2017 approved these changes

2024-01-12 01:28 UTC, max-lvs approved these changes

2024-01-12 01:32 UTC, Lighto-Ku commented
/merge

2024-01-12 01:32 UTC, merged