fix: compatible with org.desktopspec.ApplicationManager1
linuxdeepin/dde-file-manager pull request #1744
Opened 2024-01-17 07:38 UTC by ComixHe

compatible with org.desktopspec.ApplicationManager1

Log: compatible with org.desktopspec.ApplicationManager1

2024-01-17 07:56 UTC, liyigang1 requested changes

2024-01-17 07:56 UTC, liyigang1 commented on src/dfm-base/utils/universalutils.cpp
> +    auto reply = appManager.callWithArgumentList(QDBus::Block, QStringLiteral("Launch"),{
这里使用asyncCallWithArgumentList，异步调用，不要等待dbus调用回来，如果等待回来这里打开1000个文件，文件管理器就卡死了

2024-01-17 12:17 UTC, ComixHe commented on src/dfm-base/utils/universalutils.cpp
> +    auto reply = appManager.callWithArgumentList(QDBus::Block, QStringLiteral("Launch"),{
新AM的Launch本身就是异步的，下面是个MapReduce，这里需要返回值是需要判断Launch方法是否调用成功

2024-01-18 06:22 UTC, Johnson-zs approved these changes

2024-01-18 07:19 UTC, ComixHe commented
/merge

2024-01-18 07:25 UTC, BLumia approved these changes

2024-01-18 07:26 UTC, ComixHe commented
/merge

2024-01-18 07:41 UTC, ComixHe commented
/merge

2024-01-18 07:42 UTC, merged