fix: [ui] incorrect display of blank area at the bottom of the sidebar
linuxdeepin/dde-file-manager pull request #1854
Opened 2024-03-12 02:57 UTC by pppanghu77

fix incorrect display of blank area at the bottom of the sidebar and fix incorrect display of dividing lines at the bottom of the workspace

Log: fix: [ui] incorrect display of blank area at the bottom of the sidebar
Bug: https://pms.uniontech.com/bug-view-243531.html https://pms.uniontech.com/bug-view-241127.html https://pms.uniontech.com/bug-view-238993.html

2024-03-12 03:38 UTC, GongHeng2017 approved these changes

2024-03-15 01:20 UTC, itsXuSt commented on src/plugins/filemanager/core/dfmplugin-sidebar/treeviews/sidebarwidget.cpp
> +    kSidebarModelIns->addEmptyItem();
外部新增的侧边栏项可能出现在空白行的下面。

2024-03-15 01:21 UTC, itsXuSt requested changes
存在潜在 Bug

2024-03-15 06:14 UTC, pppanghu77 commented
> 存在潜在 Bug

已修复

2024-03-21 09:49 UTC, max-lvs approved these changes

2024-03-21 09:50 UTC, pppanghu77 commented
/merge

2024-03-21 09:51 UTC, merged