feat: Custom Task Turn to Main Line: dde-file-manager Clears Search History
linuxdeepin/dde-file-manager pull request #1961
Opened 2024-04-29 05:42 UTC by liyigang1

Custom Task Turn to Main Line: dde-file-manager Clears Search History

Log: Custom Task Turn to Main Line: dde-file-manager Clears Search History
Task: https://pms.uniontech.com/bug-view-252515.html

2024-05-06 06:03 UTC, Johnson-zs commented
PMS链接错了？

2024-05-06 07:30 UTC, liyigang1 commented
> PMS链接错了？

已修改

2024-05-06 07:31 UTC, Johnson-zs requested changes

2024-05-06 07:31 UTC, Johnson-zs commented on src/dfm-base/base/application/application.h
> +        KDisplaySearchHistory, // display search history
配置使用DConfig，不得再使用json

2024-05-07 03:20 UTC, liyigang1 commented on src/dfm-base/base/application/application.h
> +        KDisplaySearchHistory, // display search history
已修改

2024-05-07 09:49 UTC, Johnson-zs approved these changes

2024-05-08 00:55 UTC, liyigang1 commented
/merge

2024-05-08 00:55 UTC, merged