feat: 【 ICBC Customized Task Round to Main Line 】 Allow opening duplicate clicked folders within the same process
linuxdeepin/dde-file-manager pull request #1965
Opened 2024-04-29 09:20 UTC by liyigang1

【 ICBC Customized Task Round to Main Line 】 Allow opening duplicate clicked folders within the same process

Log: 【 ICBC Customized Task Round to Main Line 】 Allow opening duplicate clicked folders within the same process
Task: https://pms.uniontech.com/task-view-341709.html

2024-05-07 07:48 UTC, Johnson-zs requested changes

2024-05-07 07:48 UTC, Johnson-zs commented on src/dfm-base/base/application/application.h
> +        kListItemExpandable,   // Item expandable as tree in FileView with list view mode
不需要逗号

2024-05-07 07:48 UTC, Johnson-zs commented on assets/configs/org.deepin.dde.file-manager.json
> +        "dfm.open.folder.in.a.separate.process": {
名称太长了

2024-05-07 07:48 UTC, Johnson-zs commented on assets/configs/org.deepin.dde.file-manager.json
> +        "dfm.open.folder.in.a.separate.process": {
写到org.deepin.dde.file-manager.view.json去更合适

2024-05-07 07:48 UTC, Johnson-zs commented on src/plugins/filemanager/core/dfmplugin-workspace/events/workspaceeventcaller.h
> +    static void sendOpenWindow(const QList<QUrl> &urls, const bool isNew = true);
参数不应该直接用一个bool，如果未来有新的参数扩展，那么此接口又要改一次，可以用QVariant传递属性

2024-05-07 08:58 UTC, liyigang1 commented on src/dfm-base/base/application/application.h
> +        kListItemExpandable,   // Item expandable as tree in FileView with list view mode
已修改

2024-05-07 08:58 UTC, liyigang1 commented on assets/configs/org.deepin.dde.file-manager.json
> +        "dfm.open.folder.in.a.separate.process": {
已修改

2024-05-08 02:09 UTC, Johnson-zs commented on src/apps/dde-file-manager/commandparser.cpp
> +    dpfSignalDispatcher->publish(GlobalEventType::kOpenNewWindow, url, flag);
驼峰命名，kOpenFolderWindowsInASeparateProcess

2024-05-08 02:09 UTC, Johnson-zs commented on src/plugins/filemanager/core/dfmplugin-sidebar/treeviews/sidebarwidget.cpp
> +    if (flag && FileManagerWindowsManager::instance().containsCurrentUrl(target, window())) {
如果一个窗口有多个tab，其中一个tab的url和当前tab的url一样，会什么效果

2024-05-08 09:19 UTC, liyigang1 commented on src/plugins/filemanager/core/dfmplugin-sidebar/treeviews/sidebarwidget.cpp
> +    if (flag && FileManagerWindowsManager::instance().containsCurrentUrl(target, window())) {
需求说的不管tab页，只需要验证当前的显示的url

2024-05-08 09:23 UTC, liyigang1 commented on src/apps/dde-file-manager/commandparser.cpp
> +    dpfSignalDispatcher->publish(GlobalEventType::kOpenNewWindow, url, flag);
已修改

2024-05-09 01:30 UTC, Johnson-zs approved these changes

2024-05-09 01:51 UTC, liyigang1 commented
/merge

2024-05-09 01:51 UTC, merged