fix: [computer]Getting the UUID is stuck, causing the interface to freeze
linuxdeepin/dde-file-manager pull request #1984
Opened 2024-05-11 02:27 UTC by pengfeixx

Put the obtained UUID into the thread for execution

Log: Fixed some known issues

2024-05-11 03:19 UTC, itsXuSt requested changes

2024-05-11 03:19 UTC, itsXuSt commented on src/dfm-base/base/device/deviceproxymanager.cpp
> +                while (!reply.isFinished()) {
reply.waitForFinished()?

2024-05-11 03:19 UTC, itsXuSt commented on src/plugins/filemanager/core/dfmplugin-computer/private/computerview_p.h
> +    bool exit { false };
这个变量的作用是什么？

2024-05-11 03:21 UTC, itsXuSt commented on src/dfm-base/base/device/deviceproxymanager.cpp
> +            if (loop.exec()) {
这个地方不可能会进入吧？ loop.quit = loop.exit(0) 
没有出错的地方 exec 总是返回 0 吧。

2024-05-11 05:27 UTC, pengfeixx commented on src/plugins/filemanager/core/dfmplugin-computer/private/computerview_p.h
> +    bool exit { false };
> 这个变量的作用是什么？

程序退出时循环不会立即，外部函数会等待执行完后再退出，此时部分资源已经释放，加个变量防止在调用时退出崩溃

2024-05-11 05:28 UTC, pengfeixx commented on src/dfm-base/base/device/deviceproxymanager.cpp
> +            if (loop.exec()) {
> 这个地方不可能会进入吧？ loop.quit = loop.exit(0) 没有出错的地方 exec 总是返回 0 吧。

当程序退出时eventloop已经无法正常启动，这里加一个异常处理，同时阻止后续循环进入

2024-05-13 01:31 UTC, Johnson-zs requested changes

2024-05-13 01:31 UTC, Johnson-zs commented on src/dfm-base/base/device/deviceproxymanager.cpp
> +QVariantMap DeviceProxyManager::queryBlockInfo(const QString &id, bool reload, bool async)
最初设计就是一个同步的接口，此修改破坏了最初接口的理念，破坏了ABI

2024-05-13 05:11 UTC, closed without merging