fix: [computer]Getting the UUID is stuck, causing the interface to freeze
linuxdeepin/dde-file-manager pull request #1985
Opened 2024-05-13 05:31 UTC by pengfeixx

Put the obtained UUID into the thread for execution

Log: Fixed some known issues
Bug: https://pms.uniontech.com/bug-view-254659.html

2024-05-13 05:57 UTC, pengfeixx commented
/retest

2024-05-13 07:06 UTC, itsXuSt requested changes

2024-05-13 07:06 UTC, itsXuSt commented on src/dfm-base/base/device/deviceproxymanager.cpp
> +        DeviceManagerInterface devMngDBus(kDeviceService, kDevMngPath, QDBusConnection::sessionBus());
unused

2024-05-13 07:06 UTC, itsXuSt commented on src/dfm-base/base/device/deviceproxymanager.cpp
> +        return queryBlockInfo(id, reload);
你这个函数产生二义性了。这里依然是同步操作。

2024-05-13 07:14 UTC, Johnson-zs requested changes

2024-05-13 07:14 UTC, Johnson-zs commented on src/dfm-base/base/device/deviceproxymanager.cpp
> +        const auto &&info = asyncQueryBlockInfo(id);
同步接口中调用异步接口？

2024-05-13 07:14 UTC, Johnson-zs commented on src/dfm-base/base/device/deviceproxymanager.h
> +    QVariantMap queryBlockInfo(const QString &id, bool reload = false, bool async = false);
确定能编译过么

2024-05-13 08:20 UTC, pengfeixx commented on src/dfm-base/base/device/deviceproxymanager.cpp
> +        DeviceManagerInterface devMngDBus(kDeviceService, kDevMngPath, QDBusConnection::sessionBus());
> unused

已修改

2024-05-13 08:20 UTC, pengfeixx commented on src/dfm-base/base/device/deviceproxymanager.h
> +    QVariantMap queryBlockInfo(const QString &id, bool reload = false, bool async = false);
> 确定能编译过么

已修改

2024-06-06 07:41 UTC, Johnson-zs approved these changes

2024-06-06 08:18 UTC, pengfeixx commented
/merge

2024-06-06 08:18 UTC, merged