feat: [framework] init qt6 quick framework
linuxdeepin/dde-file-manager pull request #2017
Opened 2024-06-13 08:22 UTC by rb-union

* Adapt debian/control config based on qt6
* dfm-base adapt to qt6.
* Adapt framekwork with Qt6 quick;
* Add dfm-gui library;
* Block unused plugins.

Log: Init Qt6 quick framework

2024-06-14 05:19 UTC, Johnson-zs approved these changes

2024-06-14 05:19 UTC, Johnson-zs commented on include/dfm-gui/quickutils.h
> +        KUnknown,
风格上，文管采用的是小写的k

2024-06-14 05:21 UTC, Johnson-zs requested changes
调下风格

2024-06-14 06:02 UTC, rb-union commented on include/dfm-gui/quickutils.h
> +        KUnknown,
QML注册需要大写开头，按建议移除k开头字符

2024-06-17 03:01 UTC, Johnson-zs approved these changes

2024-06-17 03:02 UTC, merged