fix: Unable to drag files to disc
linuxdeepin/dde-file-manager pull request #2045
Opened 2024-06-25 05:50 UTC by liyigang1

Determine if there is a drop error

Log: Unable to drag files to disc
Bug: https://pms.uniontech.com/bug-view-260801.html

2024-06-25 06:59 UTC, Johnson-zs commented
/merge

2024-06-25 10:16 UTC, Johnson-zs requested changes

2024-06-25 10:16 UTC, Johnson-zs commented on src/dfm-base/utils/fileutils.cpp
> +    if (url.scheme() == Global::Scheme::kBurn)
burn出现在dfmbase中有特殊处理的味道了，而且burn开头的url不一定都是光盘中的文件，比如待刻录的缓存目录也是burn开头

2024-06-25 11:03 UTC, liyigang1 commented on src/dfm-base/utils/fileutils.cpp
> +    if (url.scheme() == Global::Scheme::kBurn)
好的，我修改一下

2024-06-26 02:06 UTC, Johnson-zs approved these changes

2024-06-26 02:07 UTC, merged