chore: use 1070(v20) interfaces of dde-dock
linuxdeepin/dde-file-manager pull request #2053
Opened 2024-06-26 07:14 UTC by FeiWang1119

use 1070(v20) interfaces of dde-dock in community version (v23)

Log:

2024-06-27 01:29 UTC, Johnson-zs requested changes
COMPLIE_ON_V23 在其他地方也有很多适配，不能直接删除

2024-06-27 03:51 UTC, tsic404 commented on src/external/dde-dock-plugins/disk-mount/diskmountplugin.h
> +#if (DOCK_API_VERSION >= DOCK_API_VERSION_CHECK(2, 0, 0))
下面不就是这个判断吗🤔

2024-06-27 05:42 UTC, FeiWang1119 commented on src/external/dde-dock-plugins/disk-mount/diskmountplugin.h
> +#if (DOCK_API_VERSION >= DOCK_API_VERSION_CHECK(2, 0, 0))
done

2024-06-27 07:09 UTC, Johnson-zs commented on src/external/dde-dock-plugins/disk-mount/diskmountplugin.h
这是要移除v23接口的适配么？如果是这样，那该插件代码中的COMPILE_ON_V23也需要同步处理啊

2024-06-28 09:05 UTC, FeiWang1119 commented on src/external/dde-dock-plugins/disk-mount/diskmountplugin.h
done

2024-07-01 01:41 UTC, Johnson-zs commented on src/external/dde-dock-plugins/disk-mount/diskmountplugin.cpp
> +    diskPluginItem->setVisible(true);
为什么改这里

2024-07-01 01:55 UTC, Johnson-zs approved these changes

2024-07-01 05:17 UTC, FeiWang1119 commented on src/external/dde-dock-plugins/disk-mount/diskmountplugin.cpp
> +    diskPluginItem->setVisible(true);
插了U盘, 插件里面一直不显示.也没看到它在哪个地方显示

2024-07-02 01:27 UTC, FeiWang1119 commented
/merge

2024-07-02 01:27 UTC, merged