fix: The mounted Samba network disk prompts that the file has been moved or deleted after the user changes their password
linuxdeepin/dde-file-manager pull request #2098
Opened 2024-07-10 07:14 UTC by liyigang1

When checking file information, if the host is down and can be accessed, a prompt box will pop up

Log: The mounted Samba network disk prompts that the file has been moved or deleted after the user changes their password
Bug: https://pms.uniontech.com/bug-view-261605.html

2024-07-11 08:48 UTC, max-lvs submitted a review, later dismissed

2024-07-12 01:30 UTC, Johnson-zs requested changes

2024-07-12 01:30 UTC, Johnson-zs commented on src/plugins/filemanager/core/dfmplugin-workspace/views/fileview.cpp
> +            qInfo() << rootUrl() << url << "smb server may modify password";
fmInfo

2024-07-12 01:30 UTC, Johnson-zs commented on src/dfm-base/file/local/asyncfileinfo.h
> +    DFMIOError errorDfm();
这个函数作为 const 函数好一些，其次名字很奇怪，叫 errorFromDFMIO ？

2024-07-12 02:20 UTC, liyigang1 commented on src/plugins/filemanager/core/dfmplugin-workspace/views/fileview.cpp
> +            qInfo() << rootUrl() << url << "smb server may modify password";
已修改

2024-07-12 02:20 UTC, liyigang1 commented on src/dfm-base/file/local/asyncfileinfo.h
> +    DFMIOError errorDfm();
已修改

2024-07-12 02:28 UTC, Johnson-zs approved these changes

2024-07-12 02:45 UTC, liyigang1 commented
/merge

2024-07-12 02:49 UTC, merged