fix: Less protocol DevAdded signal sent, more protocol DevRemoved signal sent
linuxdeepin/dde-file-manager pull request #2161
Opened 2024-07-31 08:10 UTC by liyigang1

Less protocol DevAdded signal sent, more protocol DevRemoved signal sent

Log: Less protocol DevAdded signal sent, more protocol DevRemoved signal sent

2024-07-31 08:22 UTC, itsXuSt requested changes
1319bb0763c30ae3240725459d1d0fa93a05e1d8
注明是在这次提交中误删，现恢复代码。

2024-07-31 08:28 UTC, liyigang1 commented
> [1319bb0](https://github.com/linuxdeepin/dde-file-manager/commit/1319bb0763c30ae3240725459d1d0fa93a05e1d8) 注明是在这次提交中误删，现恢复代码。

写了

2024-08-01 01:07 UTC, itsXuSt approved these changes

2024-08-01 02:47 UTC, max-lvs approved these changes

2024-08-02 07:41 UTC, max-lvs approved these changes

2024-08-02 08:57 UTC, merged