fix: After upgrading to version 1071, dde-file-manager monitor failed and memory continued to grow
linuxdeepin/dde-file-manager pull request #2228
Opened 2024-08-26 06:53 UTC by liyigang1

Infocache adds threads to handle the cache time of Fileinfo and FileWatcher, and exceeds the online limit

Log: After upgrading to version 1071, dde-file-manager monitor failed and memory continued to grow
Bug: https://pms.uniontech.com/bug-view-268167.html

2024-08-26 07:57 UTC, Johnson-zs requested changes

2024-08-26 07:57 UTC, Johnson-zs commented on src/dfm-base/utils/infocache.cpp
> +void InfoCache::updateSortTimeWatcherWorker(const QList<QUrl> &urls, const bool add)
函数太长分支太多，容易出bug，优化一下

2024-08-30 02:08 UTC, liyigang1 commented on src/dfm-base/utils/infocache.cpp
> +void InfoCache::updateSortTimeWatcherWorker(const QList<QUrl> &urls, const bool add)
好的

2024-08-30 02:41 UTC, max-lvs approved these changes

2024-08-30 03:04 UTC, Johnson-zs approved these changes

2024-08-30 03:04 UTC, merged