fix: When entering a file name or renaming, no prompt message is displayed after entering special characters
linuxdeepin/dde-file-manager pull request #2243
Opened 2024-08-30 09:19 UTC by liyigang1

The lack of a parent window in the tooltip resulted in loss of focus

Log: When entering a file name or renaming, no prompt message is displayed after entering special characters
Bug: https://pms.uniontech.com/bug-view-267147.html

2024-08-30 09:21 UTC, max-lvs approved these changes, later dismissed

2024-09-02 01:15 UTC, Johnson-zs requested changes

2024-09-02 01:15 UTC, Johnson-zs commented on src/plugins/filemanager/core/dfmplugin-workspace/views/iconitemeditor.cpp
> +        qCritical() << obj << qApp->focusWidget() << d->edit;
日志不规范，日志必须详细记录上下文信息，而不是只打印一个值。此外，使用fmCritical

2024-09-02 01:24 UTC, Johnson-zs approved these changes

2024-09-02 01:25 UTC, merged