fix: [filecopy]When copying large files, the swap partition is heavily used and the UI interface lags severely
linuxdeepin/dde-file-manager pull request #2336
Opened 2024-10-14 09:19 UTC by liyigang1

Modify the copying method to remove mmap and use copy_file_range

Log: When copying large files, the swap partition is heavily used and the UI interface lags severely
Bug: https://pms.uniontech.com/bug-view-273191.html

2024-10-17 02:43 UTC, Johnson-zs requested changes

2024-10-17 02:43 UTC, Johnson-zs commented on src/plugins/common/core/dfmplugin-fileoperations/fileoperations/fileoperationutils/docopyfileworker.cpp
> +                close(sourcFd);
RAII

2024-10-18 09:55 UTC, liyigang1 commented on src/plugins/common/core/dfmplugin-fileoperations/fileoperations/fileoperationutils/docopyfileworker.cpp
> +                close(sourcFd);
已处理

2024-10-18 09:59 UTC, Johnson-zs requested changes

2024-10-18 09:59 UTC, Johnson-zs commented on src/plugins/common/core/dfmplugin-fileoperations/fileoperations/fileoperationutils/docopyfileworker.cpp
> +        close(fd);
RAII

2024-10-18 09:59 UTC, Johnson-zs commented on src/plugins/common/core/dfmplugin-fileoperations/fileoperations/fileoperationutils/docopyfileworker.cpp
> +        close(sourcFd);
?

2024-10-19 03:45 UTC, max-lvs approved these changes, later dismissed

2024-10-19 05:39 UTC, liyigang1 commented on src/plugins/common/core/dfmplugin-fileoperations/fileoperations/fileoperationutils/docopyfileworker.cpp
> +        close(fd);
这里只有这一个呀，不用RAII

2024-10-19 05:40 UTC, liyigang1 commented on src/plugins/common/core/dfmplugin-fileoperations/fileoperations/fileoperationutils/docopyfileworker.cpp
> +        close(sourcFd);
立刻修改

2024-10-21 01:29 UTC, max-lvs approved these changes

2024-10-21 01:34 UTC, Johnson-zs approved these changes

2024-10-21 01:34 UTC, merged