fix: improve clipboard handling and resource management, dde-file-manager crash
linuxdeepin/dde-file-manager pull request #2501
Opened 2024-12-20 07:15 UTC by liyigang1

- Updated clipboard reading method to use static access for readFirstClipboard
- Ensured proper cleanup of local server in SingleApplication destructor
- Enhanced connection handling in ClipboardMonitor to prevent memory leaks
- Added stop method in Computer class to clear async threads
- Improved async thread management in ComputerItemWatcher
- Refactored signal-slot connections for better clarity and performance

This change enhances the clipboard handling logic by ensuring that the clipboard is read correctly and efficiently. It also improves resource management by ensuring proper cleanup of connections and async threads, preventing potential memory leaks and improving overall application stability.

Log: improve clipboard handling and resource management, dde-file-manager crash
Bug: https://pms.uniontech.com/bug-view-279983.html

2024-12-20 08:09 UTC, Johnson-zs approved these changes

2024-12-20 13:12 UTC, Johnson-zs requested changes

2024-12-20 13:12 UTC, Johnson-zs commented on src/plugins/filemanager/core/dfmplugin-computer/watcher/computeritemwatcher.cpp
> +        fw->waitForFinished();
崩溃风险

2024-12-21 02:10 UTC, liyigang1 commented on src/plugins/filemanager/core/dfmplugin-computer/watcher/computeritemwatcher.cpp
> +        fw->waitForFinished();
已修改

2024-12-23 00:55 UTC, Johnson-zs approved these changes

2024-12-23 00:55 UTC, Johnson-zs commented
/forcemerge

2024-12-23 00:55 UTC, merged