feat: Optimize view configuration and settings
linuxdeepin/dde-file-manager pull request #2504
Opened 2024-12-20 10:30 UTC by Lighto-Ku

Add new configuration items and refactor view-related settings:

1. Add new DConfig items
2. Refactor view-related constants and functions
3. Update settings dialog
4. Update view components

This change improves configuration consistency and provides better UI for view settings.

Log: Optimize view configuration and settings
Task: https://pms.uniontech.com/task-view-369577.html

2024-12-23 02:20 UTC, Johnson-zs requested changes

2024-12-23 02:20 UTC, Johnson-zs commented on include/dfm-base/dfm_global_defines.h
> +    static const QList<int> sizes = []() {
一旦用了static，它不会是线程安全的，考虑好了么

如果可以话，将这类业务单独做一个类（非单例）

2024-12-23 02:20 UTC, Johnson-zs commented on src/dfm-base/base/configs/dconfig/global_dconf_defines.h
> +/*!
视图相关配置为啥要写在dfm-base，插件内部不行吗

2024-12-23 02:20 UTC, Johnson-zs commented on include/dfm-base/settingdialog/settingjsongenerator.h
> +    bool addSliderConfig(const QString &key, const QString &name, const QString &leftIcon, const QString &rightIcon, int maxVal, int minVal, int defaultVal = 0);
不要在dfm-base中为了特殊的需求添加特殊的控件，这个控件可以worksapce插件中自己去处理

2024-12-23 02:20 UTC, Johnson-zs commented on src/dfm-base/base/configs/settingbackend.h
> +    static QPair<QWidget *, QWidget *> createSliderWithSideIcon(QObject *opt);
不能搞特殊处理

2024-12-23 02:20 UTC, Johnson-zs commented on src/plugins/filemanager/dfmplugin-workspace/utils/workspaceconfighelper.h
> +class WorkspaceConfigHelper
纯static类没有意义，不符合编码规范，直接用命名空间

2024-12-23 13:39 UTC, Lighto-Ku commented on include/dfm-base/settingdialog/settingjsongenerator.h
> +    bool addSliderConfig(const QString &key, const QString &name, const QString &leftIcon, const QString &rightIcon, int maxVal, int minVal, int defaultVal = 0);
slider算通用控件，DSlider本身支持左右图标，dtk设置配置没有提供左右图标的配置项，这里作为对slider控件的完善，增加对左右图标的配置支持。

2024-12-23 13:40 UTC, Lighto-Ku commented on src/dfm-base/base/configs/settingbackend.h
> +    static QPair<QWidget *, QWidget *> createSliderWithSideIcon(QObject *opt);
slider项控件完善，非特殊处理

2024-12-24 02:20 UTC, Johnson-zs requested changes

2024-12-24 02:20 UTC, Johnson-zs commented on include/dfm-base/settingdialog/settingjsongenerator.h
> +    bool addSliderConfig(const QString &key, const QString &name, const QString &leftIcon, const QString &rightIcon, int maxVal, int minVal, int defaultVal = 0);
这个文件在include里面，你这样改直接破坏了ABI，所以让你写到worksapce里面

2024-12-24 02:20 UTC, Johnson-zs commented on include/dfm-base/dfm_global_defines.h
> +inline constexpr char kSettingSliderItem[] { "sliderWithSideIcon" };
同样这是include的文件，涉及ABI，原则上不能乱加东西

2024-12-24 02:24 UTC, Johnson-zs requested changes

2024-12-24 02:24 UTC, Johnson-zs commented on src/dfm-base/base/configs/settingbackend.h
> +    static QPair<QWidget *, QWidget *> createSliderWithSideIcon(QObject *opt);
这个类的设计是 一个纯数据的，你在这加了个slider的控件，违背单一职责原则，非常不协调，不能放在这里

2024-12-24 07:26 UTC, Johnson-zs approved these changes

2024-12-24 07:26 UTC, Johnson-zs commented
/forcemerge

2024-12-24 07:26 UTC, merged