fix bus
linuxdeepin/dde-file-manager pull request #2513
Opened 2024-12-24 13:10 UTC by dengzhongyuan365-dev

fix: Fix the problem of deformation of the crumb menu.
    
    The rounded corner set by the system is too large. When it is displayed only one item, it cannot be completely drawn to the corner, causing the lower part of the window to abnormal. Compatible treatment will increase height when there is only one item.
    
    Log: Fix the problem of deformation of the crumb menu.
    
    Bug: https://pms.uniontech.com/bug-view-296751.html

2024-12-25 01:29 UTC, Lighto-Ku requested changes

2024-12-25 01:29 UTC, Lighto-Ku commented on src/plugins/filemanager/dfmplugin-titlebar/views/folderlistwidget.cpp
> +    }
这样修改不符合设计预期，只存在一条数据时，上下空白区域太大。

2024-12-25 02:05 UTC, Johnson-zs commented on src/plugins/filemanager/dfmplugin-titlebar/views/folderlistwidget.cpp
> +#include <dfm-base/utils/chinese2pinyin.h>
头文件位置没放对

2024-12-25 02:46 UTC, dengzhongyuan365-dev commented on src/plugins/filemanager/dfmplugin-titlebar/views/folderlistwidget.cpp
> +    }
这里和周倩讨论过，因为系统的圆角在只有一项的时候会绘制不全，出现残角。就还是加高让他显示正常。

2024-12-25 02:50 UTC, dengzhongyuan365-dev commented on src/plugins/filemanager/dfmplugin-titlebar/views/folderlistwidget.cpp
> +#include <dfm-base/utils/chinese2pinyin.h>
已经修改

2024-12-26 02:09 UTC, Johnson-zs approved these changes

2024-12-26 02:24 UTC, Johnson-zs commented
/forcemerge

2024-12-26 02:24 UTC, merged