BUG: laggy background change after switch between workspace
linuxdeepin/dde-file-manager pull request #306
Opened 2020-11-22 10:56 UTC by MrMorteZw

this change will fix laggy switch workspace

2022-04-29 09:11 UTC, max-lvs commented
hello， thanks for your PR, but before review the code you can take one issue to repeat this and we can verify it.

2022-07-01 06:32 UTC, wangchunlin5013 requested changes

2022-07-01 06:32 UTC, wangchunlin5013 commented on dde-desktop/view/backgroundmanager.cpp
> +        //更新壁纸
Update in cycle? This is definitely not a good idea.
In addition，bw->setPixmap(pix) has actually updated the picture.

2022-11-08 09:15 UTC, itsXuSt commented
Long time no update, close.

2022-11-08 09:15 UTC, closed without merging