feat: Optimize computer-view component performance
linuxdeepin/dde-file-manager pull request #451
Opened 2022-06-15 09:35 UTC by myml

suffix function are called frequently,
share regular expression and cache match result

Log: 提高计算机视图的性能

Before
![截图_选择区域_20220615173218](https://user-images.githubusercontent.com/13045857/173795319-69d47f39-bd0d-431b-91ed-52d44a3aba28.png)

After
![截图_选择区域_20220615173250](https://user-images.githubusercontent.com/13045857/173795414-34acd831-37d5-43c2-8110-fd4e1bd2cf77.png)

2022-06-22 02:25 UTC, itsXuSt commented on src/dde-file-manager-lib/models/dfmrootfileinfo.cpp
> +QHash<QString, QString> suffixCache;
1. global variable is not good;
2. the key of cache can be duplicated, for udisk, 'fileName' is the label of disk, and different udisk could have same name. UUID for disk is unique but protocol (smb/ftp/sftp/mtp...) mount do not have one;
3. the cache is never cleaned, may cause problem;

2022-06-22 02:31 UTC, itsXuSt commented
SO NO.

2022-06-22 02:32 UTC, itsXuSt requested changes

2022-06-22 02:32 UTC, itsXuSt commented on src/dde-file-manager-lib/models/dfmrootfileinfo.cpp
> +QHash<QString, QString> suffixCache;
keep contributing if you find any other better solution.

2022-07-27 07:53 UTC, myml commented on src/dde-file-manager-lib/models/dfmrootfileinfo.cpp
> +QHash<QString, QString> suffixCache;
1. 全局变量的问题解决了
2. 哈希表缓存的是卷表的正则匹配结果，相同字符串结果也应该是相同的，应该不需要考虑同名问题吧？
3. 正常情况下，卷的数量应该不会非常多，为了避免异常情况，给哈希表添加了大小限制，存储超过50个进行一次清理。

2022-07-27 08:11 UTC, myml commented
/review itsXuSt

2022-07-29 06:46 UTC, itsXuSt commented on src/dde-file-manager-lib/models/dfmrootfileinfo.cpp
> +QHash<QString, QString> suffixCache;
文件管理器计算机页面现在有很多种设备类型，后缀有以下几种： 
userdir（用户目录节点），
gvfsmp（通过gvfs挂载的设备节点），
localdisk（常规块设备节点），
remote（samba 离线常驻节点），
appentry（应用入口节点）

这些不同类型 suffix 对应的 RootFileInfo 可能重名，比如，可以“视频.userdir”与 “视频.localdisk” 重名，但你的缓存键值是“视频”，就会导致后来的这个视频磁盘的类型变成了 userdir 但它应该是磁盘类型，从而有了期望之外的表现结果。
以及 remote 与 gvfsmp 可能产生重名，appentry 可能与任意一个产生重名。

2022-08-02 07:29 UTC, myml commented on src/dde-file-manager-lib/models/dfmrootfileinfo.cpp
> +QHash<QString, QString> suffixCache;
缓存键用的是全名，不是后缀，后缀是做为缓存的值，比如"视频.userdir" 缓存的键是“视频.userdir”，值是"userdir"。

我理解的是，同一个正则表达式，如果输入(全名)相同，输出(后缀)应该也是相同的，所以我用了哈西表来存储这个正则表达式的输入和输出。因为这个正则表达式调用的非常频繁。

2023-03-10 03:00 UTC, myml commented
问题已经解决

2023-03-10 03:00 UTC, closed without merging