feat: remove the file:// when copy url
linuxdeepin/dde-file-manager pull request #469
Opened 2022-07-13 06:23 UTC by kt286

remove the file:// when copy url

Log: remove the file:// when copy url

2022-07-13 07:14 UTC, zccrs requested changes

2022-07-13 07:14 UTC, zccrs commented on src/dde-file-manager-lib/interfaces/dfmcrumbbar.cpp
> +        QGuiApplication::clipboard()->setText(virtualUrl.replace(FILE_ROOT, "/"));
这样直接替换不够严谨。可以通过 QUrl::isLocalFile 判断是不是一个本地文件，如果是的，那就只往剪切板里写入 url.path()，而不是 url.toString()

2022-07-15 05:44 UTC, itsXuSt submitted a review, later dismissed

2022-07-20 05:05 UTC, zccrs requested changes

2022-07-20 05:05 UTC, zccrs commented on src/dde-file-manager-lib/interfaces/dfmcrumbbar.cpp
> +        if (url.isLocalFile()) {
这个判断还要跟 if (VaultController::isVaultFile(virtualUrl))，应该在它的else中判断，然后 virtualUrl = url.toLocalFile(). 最后是 QGuiApplication::clipboard()->setText(virtualUrl); 设置数据。

2022-07-29 07:43 UTC, itsXuSt commented
/+1

2022-07-29 07:45 UTC, itsXuSt approved these changes

2022-07-29 07:49 UTC, kt286 commented
/merge

2022-07-29 08:18 UTC, zccrs approved these changes

2022-07-29 08:18 UTC, zccrs commented
/merge

2022-07-29 08:19 UTC, merged