feat: [hide remind] rename file remind when file name startwith '.'
linuxdeepin/dde-file-manager pull request #590
Opened 2022-09-13 06:16 UTC by misonlan

rename file remind when file name startwith '.'

Log: rename remind

Task: https://pms.uniontech.com/task-view-190087.html

2022-09-13 08:57 UTC, itsXuSt requested changes
提交信息中不要添加内网信息

2022-09-13 09:00 UTC, misonlan commented
> 提交信息中不要添加内网信息

2022-09-13 09:02 UTC, misonlan commented
> > 提交信息中不要添加内网信息

done

2022-09-13 12:05 UTC, misonlan commented
/check

2022-09-14 08:57 UTC, Johnson-zs approved these changes

2022-09-14 09:10 UTC, itsXuSt approved these changes

2022-09-14 09:10 UTC, merged