fix: Fixed the bug that document icon appears as pdf icon
linuxdeepin/dde-file-manager pull request #626
Opened 2022-10-14 07:13 UTC by obslee

as title

Log: Fixed the bug that document icon appears as pdf icon
Bug: https://pms.uniontech.com/bug-view-155717.html

2022-10-14 08:03 UTC, itsXuSt requested changes
缩进异常

2022-10-14 08:03 UTC, misonlan submitted a review, later dismissed

2022-10-14 08:23 UTC, itsXuSt requested changes
编码风格问题较多

2022-10-14 08:23 UTC, itsXuSt commented on src/dde-file-manager-lib/shutil/fileutils.cpp
> +    g_autoptr(GFile) gfile = g_file_new_for_uri(url.toString().toLocal8Bit().data());
url.tostring.**tostdstring**.c_str()

2022-10-14 08:23 UTC, itsXuSt commented on src/dde-file-manager-lib/shutil/fileutils.cpp
> +    gfileInfo = g_file_query_info(gfile, "standard::icon", G_FILE_QUERY_INFO_NONE, nullptr, nullptr);
可合并一行

2022-10-14 08:23 UTC, itsXuSt commented on src/dde-file-manager-lib/shutil/fileutils.cpp
> +    if(names && names[0] != nullptr)
names && names[0] 指针判定无需 /*!= nullptr*/

2022-10-14 08:45 UTC, itsXuSt commented
/approve

2022-10-17 06:19 UTC, obslee commented on src/dde-file-manager-lib/shutil/fileutils.cpp
> +    g_autoptr(GFile) gfile = g_file_new_for_uri(url.toString().toLocal8Bit().data());
done

2022-10-19 02:20 UTC, Clauszy commented on src/dde-file-manager-lib/shutil/fileutils.cpp
> +    g_autoptr(GFile) gfile = g_file_new_for_uri(url.toString().toStdString().c_str());
url.toString().toStdString().c_str() 危险写法

2022-10-19 02:20 UTC, Clauszy commented on src/dde-file-manager-lib/shutil/fileutils.cpp
> +        return QString::fromLocal8Bit(names[0]);
不判断越界？

2022-10-19 02:21 UTC, misonlan commented on src/dde-file-manager-lib/shutil/fileutils.cpp
> +    if (names)
这里返回的是char**，需要判断names和names[0]

2022-12-20 09:36 UTC, closed without merging