feat: Smb integration swither with a notice
linuxdeepin/dde-file-manager pull request #640
Opened 2022-10-25 03:39 UTC by shzhuangpub

Implement a notice under checkbox.

Log: Smb integration swither with a notice
Task: https://pms.uniontech.com/task-view-201173.html

2022-10-25 09:05 UTC, itsXuSt requested changes

2022-10-25 09:05 UTC, itsXuSt commented on src/dde-file-manager-lib/configure/global-setting-template-fedora.js
> +                            "type": "mergeSmbCheckBox",
不建议给其命名为这个。
建议封装为 CheckboxWithMessage
以便复用

2022-10-25 09:17 UTC, shzhuangpub commented on src/dde-file-manager-lib/configure/global-setting-template-fedora.js
> +                            "type": "mergeSmbCheckBox",
好的。

2022-10-27 07:02 UTC, itsXuSt approved these changes

2022-10-27 07:04 UTC, shzhuangpub commented
/approve

2022-10-27 07:09 UTC, Johnson-zs approved these changes

2022-10-27 07:10 UTC, shzhuangpub commented
/approve

2022-10-27 07:14 UTC, merged