fix: Asking password dialog doesnt popup after forgetting pw and unmounting
linuxdeepin/dde-file-manager pull request #676
Opened 2022-11-08 08:44 UTC by shzhuangpub

1. Clear login data when mount smb with split mode;
2. Set saving password type to never-save mode when mount smb with split mode.

Bug: https://pms.uniontech.com/bug-view-170201.html

2022-11-08 09:00 UTC, itsXuSt requested changes

2022-11-08 09:00 UTC, itsXuSt commented on src/dde-file-manager-lib/gvfs/gvfsmountmanager.cpp
> +        while (!m_loginObj.isEmpty()) {
等效于 m_loginObj.clear ?

2022-11-08 09:00 UTC, itsXuSt commented on src/dde-file-manager-lib/gvfs/gvfsmountmanager.cpp
> +            if (m_mountScheme == SMB_SCHEME) {
！smb 的 passwordSave 字段缺失 ，savePasswordChecked 字段恒为 false

2022-11-08 09:00 UTC, itsXuSt commented on src/dde-file-manager-lib/gvfs/gvfsmountmanager.cpp
> +            if (saveType == int(GPasswordSave::G_PASSWORD_SAVE_PERMANENTLY)) { // 勾选了记住密码(smb、ftp、sftp)
勾选记住密码的状态存储在 savePasswordChecked 里，从 passwordSave 里拿到的恒为不保存和单次会话保存

2022-11-08 09:00 UTC, itsXuSt commented on src/dde-file-manager-lib/gvfs/gvfsmountmanager.cpp
> +                if (saveType == int(GPasswordSave::G_PASSWORD_SAVE_FOR_SESSION)) { // smb聚合模式设置的单次回话记住密码
会话，错别字。

2022-11-08 09:04 UTC, shzhuangpub commented on src/dde-file-manager-lib/gvfs/gvfsmountmanager.cpp
> +        while (!m_loginObj.isEmpty()) {
QJsonObject没有clear方法。

2022-11-08 09:25 UTC, shzhuangpub commented on src/dde-file-manager-lib/gvfs/gvfsmountmanager.cpp
> +            if (m_mountScheme == SMB_SCHEME) {
从鉴权对话框点击确认之后，返回的m_loginObj里面一定有"passwordSave"字段，不会缺失，这里把多余的952行去掉了，因为"passwordSave"字段在鉴权对话框里已经设置了。

2022-11-08 09:49 UTC, shzhuangpub commented on src/dde-file-manager-lib/gvfs/gvfsmountmanager.cpp
> +            if (saveType == int(GPasswordSave::G_PASSWORD_SAVE_PERMANENTLY)) { // 勾选了记住密码(smb、ftp、sftp)
勾选记住密码的状态是存储在 passwordsaveFlag 里的（0或2），它的值来自鉴权对话框。而savePasswordChecked变量用于标识用户挂载smb时是否勾选过记住密码，它会进入Samba.json。其实Samba.json里面，passwordSave为2时，savePasswordChecked就为true，passwordSave为1时，savePasswordChecked就为false。savePasswordChecked就是多余的，要去掉它。

2022-11-09 02:34 UTC, itsXuSt approved these changes

2022-11-09 02:39 UTC, merged