i18n: mount plugin generate ts files
linuxdeepin/dde-file-manager pull request #74
Opened 2019-03-21 07:15 UTC by BLumia

还没有改 mount plugin 读取翻译的地方，先看看有没有问题，以及能不能让 dock 插件不要处理配置文件相关的翻译。

2019-03-21 07:26 UTC, zccrs requested changes

2019-03-21 07:26 UTC, zccrs commented on dde-dock-plugins/disk-mount/disk-mount.pro
>  INSTALLS += target
添加 translations

2019-03-21 07:26 UTC, zccrs commented on dde-dock-plugins/disk-mount/disk-mount.pro
> +translations.path = $$APPSHAREDIR/translations
path = $${PREFIX}/share/$${TARGET}/translations

2019-03-21 07:26 UTC, zccrs commented on dde-dock-plugins/disk-mount/disk-mount.pro
> +translations.path = $$APPSHAREDIR/translations
另外将此目录加到 dde-disk-mount-plugin.install

2019-03-21 07:26 UTC, zccrs commented on dde-file-manager-lib/translations/dde-file-manager.ts
>          <translation type="unfinished"></translation>
避免不必要的文件改动

2019-03-21 08:52 UTC, zccrs requested changes

2019-03-21 08:52 UTC, zccrs commented on dde-dock-plugins/disk-mount/diskmountplugin.cpp
>  {
需要加载翻译文件

2019-03-22 02:18 UTC, listenerri approved these changes

2019-03-22 02:46 UTC, zccrs approved these changes

2019-03-22 02:53 UTC, merged