fix: [drag&drop] Disable drag-and-drop recent files to the trash
linuxdeepin/dde-file-manager pull request #836
Opened 2023-04-14 08:54 UTC by Kakueeen

as title
Log: fix bug
Bug: https://pms.uniontech.com/bug-view-194133.html
Bug: https://pms.uniontech.com/bug-view-194131.html

2023-04-14 09:48 UTC, Clauszy commented on include/dfm-base/dfm_global_defines.h
> +inline constexpr char kDFMMimeDataKey[] { "dfm_mimedata" };
这个名字会不会太大了，可以加上drag之类的限定符。

2023-04-14 09:55 UTC, Kakueeen commented on include/dfm-base/dfm_global_defines.h
> +inline constexpr char kDFMMimeDataKey[] { "dfm_mimedata" };
done

2023-04-18 01:42 UTC, GongHeng2017 reviewed
+1

2023-04-18 01:45 UTC, max-lvs submitted a review, later dismissed
+2

2023-04-18 01:46 UTC, liyigang1 approved these changes, later dismissed

2023-04-18 01:56 UTC, Johnson-zs commented on src/dfm-base/mimedata/dfmmimedata.h
> +    QSharedPointer<DFMMimeDataPrivate> d;
多个DFMMimeData共享一个私有类对象？这里建议使用QShareData

2023-04-18 02:00 UTC, Johnson-zs commented on src/dfm-base/mimedata/dfmmimedata.h
> +}
namespace 最后的大括号后面加注释 // namespace dfmbase

2023-04-18 02:00 UTC, Johnson-zs commented on src/plugins/filemanager/core/dfmplugin-workspace/views/fileview.cpp
> +        data->setData(DFMGLOBAL_NAMESPACE::Mime::kDFMMimeDataKey, dfmmimeData.toByteArray());
这里现在数据重复了吧

2023-04-18 02:16 UTC, Clauszy requested changes
自动整理插件也需要修改

2023-04-18 05:08 UTC, Johnson-zs commented on src/dfm-base/mimedata/dfmmimedata.h
> +    QSharedPointer<DFMMimeDataPrivate> d;
这里应该使用QSharedDataPointer

2023-04-18 05:11 UTC, liyigang1 submitted a review, later dismissed

2023-04-18 06:50 UTC, Johnson-zs approved these changes

2023-04-18 06:58 UTC, Clauszy approved these changes

2023-04-18 06:59 UTC, max-lvs approved these changes

2023-04-18 07:00 UTC, Kakueeen commented
/merge

2023-04-18 07:00 UTC, merged