fix: When there are too many files in the trash, the operation gets stuck
linuxdeepin/dde-file-manager pull request #837
Opened 2023-04-14 09:42 UTC by liyigang1

There are issues with the process of using the drawing interface. 1. Modify the use of Fileinfo for tag drawing events in list and icon modes. 2. Modify the corner markers and also use fileinfo. 3. When receiving file information, corner markers, and thumbnail signals, only the corresponding areas will be updated. 4. Modify the completion signal of the extended corner marker, and do not send it if there is none. 5. The order and sorting displayed first in sortworker are the same, and the interface is not updated. 6. When receiving changes in the status of the recycle bin, do not refresh all items and use the trashrooturl to update the specified items.

Log: When there are too many files in the trash, the operation gets stuck
Bug: https://pms.uniontech.com/bug-view-189691.html

2023-04-14 10:01 UTC, itsXuSt requested changes
fix: [xxxxx]

2023-04-17 01:58 UTC, Johnson-zs commented
1. 不同的修改，分为多个commits提交
2. 为什么把url改成fileinfo，根因？

2023-04-18 02:51 UTC, liyigang1 commented
> fix: [xxxxx]

已添加

2023-04-18 02:52 UTC, liyigang1 commented
> 1. 不同的修改，分为多个commits提交
> 2. 为什么把url改成fileinfo，根因？

已修改

2023-04-18 07:14 UTC, Johnson-zs approved these changes

2023-04-18 07:22 UTC, merged