fix: [workspace/emblem] view optimization
linuxdeepin/dde-file-manager pull request #838
Opened 2023-04-14 10:34 UTC by Lighto-Ku

1.paint emblems by fileinfo from model.
2.get tags by fileinfo from model.

Log: view optimization

Bug: https://pms.uniontech.com/bug-view-195757.html

2023-04-17 02:00 UTC, Johnson-zs requested changes
why？

2023-04-17 02:34 UTC, Lighto-Ku commented
> why
不使用fileinfo缓存的异步获取场景下，通过url获取角标或标记的话，会在过程中再次创建fileinfo，新的fileinfo又会触发异步刷新的逻辑，陷入无限循环。直接在接口中传fileinfo，避免再次创建fileinfo。

2023-04-17 03:46 UTC, Johnson-zs commented
> > why？
> 
> 不使用fileinfo缓存的异步获取场景下，通过url获取角标或标记的话，会在过程中再次创建fileinfo，新的fileinfo又会触发异步刷新的逻辑，陷入无限循环。直接在接口中传fileinfo，避免再次创建fileinfo。

fileinfo机制的改动对业务插件是个黑盒，不太赞同由各个业务插件去反向适配

2023-04-17 03:52 UTC, Lighto-Ku commented
> > > why？
> > 
> > 
> > 不使用fileinfo缓存的异步获取场景下，通过url获取角标或标记的话，会在过程中再次创建fileinfo，新的fileinfo又会触发异步刷新的逻辑，陷入无限循环。直接在接口中传fileinfo，避免再次创建fileinfo。
> 
> fileinfo机制的改动对业务插件是个黑盒，不太赞同由各个业务插件去反向适配

也不是插件针对fileinfo的适配，实质上是workspace对外扩展接口的设计做了调整，尽量让外部插件直接使用model中已准备好的数据

2023-04-17 06:30 UTC, Johnson-zs approved these changes

2023-04-18 01:06 UTC, liyigang1 approved these changes

2023-04-18 01:54 UTC, merged