fix: [workspace]drag optimization
linuxdeepin/dde-file-manager pull request #863
Opened 2023-04-20 08:33 UTC by Lighto-Ku

1.fetch urls from mimedata when drag enter and cache them for dragMove. 
2.add block mount report.

Log: drag optimization
Bug: https://pms.uniontech.com/bug-view-194099.html

2023-04-20 09:41 UTC, Johnson-zs requested changes

2023-04-20 09:41 UTC, Johnson-zs commented on src/plugins/common/dfmplugin-burn/utils/discstatemanager.cpp
> +                dpfSignalDispatcher->publish("dfmplugin_burn", "signal_ReportLog_BlockMountData", QVariantMap({{"dev", id}, {"result", ok}}));
不太建议在每个插件发送挂载埋点的方法，最好统一处理

2023-04-21 03:32 UTC, itsXuSt requested changes

2023-04-21 03:32 UTC, itsXuSt commented on src/dfm-base/base/device/devicemanager.h
> +    void aboutToBlockDevMount(const QString &id, bool result);
blockDevAboutToMount

2023-04-21 03:43 UTC, Johnson-zs commented on src/dfm-base/base/device/devicemanager.cpp
> +            this->aboutToBlockDevMount(id, ok);
+emit

2023-04-21 05:24 UTC, Johnson-zs approved these changes

2023-04-21 05:31 UTC, max-lvs approved these changes
+2

2023-04-21 05:33 UTC, itsXuSt approved these changes

2023-04-21 05:35 UTC, Lighto-Ku commented
/merge

2023-04-21 05:35 UTC, merged