chore: [Vault] add UT
linuxdeepin/dde-file-manager pull request #875
Opened 2023-04-23 09:55 UTC by GongHeng2017

as title

Log: add Vault UT

2023-04-23 10:00 UTC, itsXuSt commented on tests/plugins/filemanager/dfmplugin-vault/ut_vault.cpp
> +#define private public
不需要用这个，加了编译参数，没有公私差异。

2023-04-23 10:00 UTC, itsXuSt requested changes
不要使用 #define private public

2023-04-24 01:08 UTC, GongHeng2017 commented on tests/plugins/filemanager/dfmplugin-vault/ut_vault.cpp
> +#define private public
done

2023-04-24 01:52 UTC, max-lvs commented on tests/plugins/filemanager/dfmplugin-vault/ut_vault.cpp
> +    EXPECT_NO_FATAL_FAILURE(ins.initialize());
请先做功能点覆盖，不要做代码覆盖率，EXPECT_NO_FATAL_FAILURE 就是纯跑分的。

2023-04-24 03:41 UTC, GongHeng2017 commented on tests/plugins/filemanager/dfmplugin-vault/ut_vault.cpp
> +    EXPECT_NO_FATAL_FAILURE(ins.initialize());
done

2023-04-24 03:45 UTC, max-lvs approved these changes, later dismissed
+2

2023-04-24 05:52 UTC, itsXuSt approved these changes

2023-04-24 05:54 UTC, Kakueeen approved these changes

2023-04-24 05:57 UTC, max-lvs approved these changes

2023-04-24 05:59 UTC, GongHeng2017 commented
/merge

2023-04-24 05:59 UTC, merged

2023-04-24 06:05 UTC, Johnson-zs commented on tests/plugins/filemanager/dfmplugin-vault/views/removevaultview/ut_vaultremoveprogressview.cpp
> +    QDir dir("/test123");
依然去操作了真实文件