feat: [io]write ut
linuxdeepin/dde-file-manager pull request #884
Opened 2023-04-24 08:38 UTC by liyigang1

Write ut for classes fileoperationsutils, workdata, abstractworker, abstractjob, errormassageandaction

Log: Write ut for classes fileoperationsutils, workdata, abstractworker, abstractjob, errormassageandaction
Task: https://pms.uniontech.com/task-view-257955.html

2023-04-24 08:43 UTC, itsXuSt requested changes
test: [ut] ut for xxxxxxxxx

2023-04-24 08:49 UTC, itsXuSt requested changes

2023-04-24 08:49 UTC, itsXuSt commented on tests/plugins/common/core/dfmplugin-fileoperations/fileoperations/fileoperations/fileoperationutils/ut_abstrackjob.cpp
> +    ~UT_AbstractJob() override;
不需要。

2023-04-24 08:49 UTC, itsXuSt commented on tests/plugins/common/core/dfmplugin-fileoperations/fileoperations/fileoperations/fileoperationutils/ut_abstrackjob.cpp
> +
空行

2023-04-24 08:49 UTC, itsXuSt commented on tests/plugins/common/core/dfmplugin-fileoperations/fileoperations/fileoperations/fileoperationutils/ut_abstrackjob.cpp
> +    stub.set_lamda(VADDR(AbstractWorker, doWork), []{ return false; });
建议使用 `__DBG_STUB_INVOKE__` 宏以方便确认桩函数是否有调用。

2023-04-24 08:49 UTC, itsXuSt commented on tests/plugins/common/core/dfmplugin-fileoperations/fileoperations/fileoperations/fileoperationutils/ut_fileoperationsutils.cpp
> +    QProcess::execute("rm -rf ./testAsyncFileInfo");
不是说不让访问真实资源么？

2023-04-24 08:49 UTC, itsXuSt commented on tests/plugins/common/core/dfmplugin-fileoperations/fileoperations/fileoperations/fileoperationutils/ut_fileoperationsutils.cpp
> +    UpdateProgressTimer timer;
没有任何检查点的用例

2023-04-24 08:49 UTC, itsXuSt commented on tests/plugins/common/core/dfmplugin-fileoperations/fileoperations/fileoperations/fileoperationutils/ut_workdata.cpp
> +    WorkerData data;
无意义用例。

2023-04-24 09:46 UTC, max-lvs reviewed
feat: [io]write ut  -->  
test: [io]write ut (可以补充点东西，title太简单了)

2023-04-25 03:09 UTC, liyigang1 commented
> test: [ut] ut for xxxxxxxxx

已修改

2023-04-25 03:09 UTC, liyigang1 commented
> feat: [io]write ut --> test: [io]write ut (可以补充点东西，title太简单了)

已修改

2023-04-25 03:09 UTC, liyigang1 commented on tests/plugins/common/core/dfmplugin-fileoperations/fileoperations/fileoperations/fileoperationutils/ut_fileoperationsutils.cpp
> +    UpdateProgressTimer timer;
已修改

2023-04-25 05:52 UTC, Johnson-zs commented on tests/plugins/common/core/dfmplugin-fileoperations/fileoperations/fileoperations/fileoperationutils/ut_fileoperationsutils.cpp
> +    QProcess::execute("mkdir ./testAsyncFileInfo");
？

2023-04-25 06:15 UTC, liyigang1 commented on tests/plugins/common/core/dfmplugin-fileoperations/fileoperations/fileoperations/fileoperationutils/ut_fileoperationsutils.cpp
> +    QProcess::execute("mkdir ./testAsyncFileInfo");
不允许使用真实资源？

2023-04-25 06:49 UTC, Johnson-zs commented on tests/plugins/common/core/dfmplugin-fileoperations/fileoperations/fileoperations/fileoperationutils/ut_fileoperationsutils.cpp
> +    QProcess::execute("mkdir ./testAsyncFileInfo");
嗯

2023-04-26 01:58 UTC, liyigang1 commented on tests/plugins/common/core/dfmplugin-fileoperations/fileoperations/fileoperations/fileoperationutils/ut_fileoperationsutils.cpp
> +    QProcess::execute("mkdir ./testAsyncFileInfo");
已修改

2023-04-26 02:01 UTC, GongHeng2017 reviewed
+1

2023-04-26 02:09 UTC, max-lvs approved these changes
+2

2023-04-26 05:11 UTC, liyigang1 commented
/merge && rebase

2023-04-26 05:11 UTC, merged