Fix build on openSUSE
linuxdeepin/dde-file-manager pull request #915
Opened 2023-04-29 04:48 UTC by hillwoodroc

2023-04-29 05:26 UTC, BLumia requested changes

2023-04-29 05:26 UTC, BLumia commented on src/apps/dde-desktop/CMakeLists.txt
> +set(CMAKE_C_FLAGS "${CMAKE_CXX_FLAGS} -fPIC")
```suggestion
set(CMAKE_C_FLAGS "${CMAKE_C_FLAGS} -fPIC")
```

下同。这全错了= =

2023-04-29 07:52 UTC, hillwoodroc commented on src/apps/dde-desktop/CMakeLists.txt
> +set(CMAKE_C_FLAGS "${CMAKE_CXX_FLAGS} -fPIC")
汗，复制粘贴一把梭没看清楚。这回都改了。

2023-05-05 01:42 UTC, Johnson-zs approved these changes

2023-05-05 01:45 UTC, BLumia approved these changes

2023-05-05 02:17 UTC, BLumia commented
/merge

2023-05-05 02:17 UTC, merged