fix: [io/workspace]Rename unsuccessful
linuxdeepin/dde-file-manager pull request #945
Opened 2023-05-08 06:22 UTC by liyigang1

An asynchronous FileInfo was created before renaming, causing information to be queried for files under mtp, resulting in MTP device busy at the time of renaming. The previous MTP information query completed when the file was added on the interface, but this is the file information query that was not created the last time the file was added, so it determines whether the file exists or is an error. Modify 1. Fileinfo is created synchronously before renaming (asynchronous for next phase optimization, waiting for asynchronous queries to complete). 2. When adding a file, do the file information again

Log: Rename unsuccessful
Bug: https://pms.uniontech.com/bug-view-197913.html

2023-05-08 08:37 UTC, Lighto-Ku requested changes

2023-05-08 08:37 UTC, Lighto-Ku commented on src/plugins/common/core/dfmplugin-fileoperations/fileoperations/fileoperationutils/fileoperatebaseworker.cpp
> +    // has three char " ", so data has 4 item, the 3th is the "Path=%E6%96%B0%E5%BB%BAWord%E6%96%87%E6%A1%A3.doc"
无意义的注释

2023-05-08 08:37 UTC, Lighto-Ku commented on src/plugins/filemanager/core/dfmplugin-workspace/models/rootinfo.cpp
> +        emit InfoCacheController::instance().removeCacheFileInfo(removeUrls);
为什么在这里移除文件信息缓存？

2023-05-08 09:17 UTC, liyigang1 commented on src/plugins/common/core/dfmplugin-fileoperations/fileoperations/fileoperationutils/fileoperatebaseworker.cpp
> +    // has three char " ", so data has 4 item, the 3th is the "Path=%E6%96%B0%E5%BB%BAWord%E6%96%87%E6%A1%A3.doc"
这是军哥要求的注释,不然都不知道为什么这么去取

2023-05-08 09:17 UTC, liyigang1 commented on src/plugins/filemanager/core/dfmplugin-workspace/models/rootinfo.cpp
> +        emit InfoCacheController::instance().removeCacheFileInfo(removeUrls);
我文件都删除掉了,留着这个fileinfo没有用

2023-05-08 10:04 UTC, Lighto-Ku approved these changes

2023-05-09 03:45 UTC, Kakueeen approved these changes

2023-05-09 03:50 UTC, max-lvs commented on src/plugins/filemanager/core/dfmplugin-workspace/models/rootinfo.cpp
> +        child->refresh();
每次都刷新一下，性能会不会上不去？加载更慢了。不是有异步回调么？

2023-05-09 03:52 UTC, max-lvs approved these changes

2023-05-09 05:18 UTC, liyigang1 commented on src/plugins/filemanager/core/dfmplugin-workspace/models/rootinfo.cpp
> +        child->refresh();
不是，这个接口是filewatcher监视到文件在异步线程中调用的

2023-05-09 05:18 UTC, liyigang1 commented
/merge && rebase

2023-05-09 05:18 UTC, merged