fix: [vault] When 1000+ files, the vault card
linuxdeepin/dde-file-manager pull request #978
Opened 2023-05-16 09:33 UTC by GongHeng2017

1. let the vault fileinfo in cache
2. create the vault fileinfo, let it cache
3. create the vault fileinfo by vaultfileiterator, let it cache

Log: Optimize the safe of the safe
Bug: https://pms.uniontech.com/bug-view-199947.html

2023-05-16 09:52 UTC, max-lvs commented on include/dfm-base/base/schemefactory.h
> +                                    bool isUseCache = false,
当前设备只分快速设备、慢速设备。保险箱需要根据自己的特性定义好自己的分类。不能因为分类不准确而增加或修改现有接口造成破窗效应。
快速设备的接口优化是另外一个话题，提出、方案、论证、各个模块修改 是一系列工作。而不应该在此反应。

2023-05-17 03:16 UTC, Johnson-zs requested changes

2023-05-17 03:16 UTC, Johnson-zs commented on src/dfm-base/utils/fileutils.cpp
>  QSet<QUrl> FileUtils::copyingUrl;
不能定义全局变量，这个方案的实现要考虑换个位置

2023-05-17 03:31 UTC, Johnson-zs requested changes

2023-05-17 03:31 UTC, Johnson-zs commented on src/dfm-base/utils/fileutils.cpp
> +    if (localDeviceJudgeFuncMap.count() > 0) {
这里破坏了isLocalDevice这个接口的本意，无法保证代码的正交性，可以通过新增isSlowDevie来实现

2023-05-18 03:39 UTC, liyigang1 submitted a review, later dismissed

2023-05-18 03:41 UTC, GongHeng2017 commented on include/dfm-base/base/schemefactory.h
> +                                    bool isUseCache = false,
done
重新实现

2023-05-18 03:43 UTC, GongHeng2017 commented on src/dfm-base/utils/fileutils.cpp
>  QSet<QUrl> FileUtils::copyingUrl;
done

2023-05-18 03:47 UTC, Kakueeen commented on src/dfm-base/base/schemefactory.cpp
> +        emit InfoCacheController::instance().cacheFileInfo(url, info);
info为空也要缓存吗

2023-05-18 03:49 UTC, GongHeng2017 commented on src/dfm-base/base/schemefactory.cpp
> +        emit InfoCacheController::instance().cacheFileInfo(url, info);
done

2023-05-18 03:57 UTC, GongHeng2017 commented on src/dfm-base/utils/fileutils.cpp
> +    if (localDeviceJudgeFuncMap.count() > 0) {
done

2023-05-18 04:12 UTC, liyigang1 submitted a review, later dismissed

2023-05-18 04:20 UTC, Johnson-zs approved these changes, later dismissed

2023-05-18 05:05 UTC, Kakueeen approved these changes, later dismissed

2023-05-18 05:05 UTC, GongHeng2017 commented
/merge

2023-05-18 05:23 UTC, Clauszy approved these changes, later dismissed

2023-05-18 05:25 UTC, GongHeng2017 commented
/merge

2023-05-18 05:33 UTC, liyigang1 approved these changes, later dismissed

2023-05-18 05:51 UTC, GongHeng2017 commented
/merge

2023-05-18 05:53 UTC, GongHeng2017 commented
/merge

2023-05-18 05:54 UTC, GongHeng2017 commented
/merge

2023-05-18 06:01 UTC, Johnson-zs approved these changes

2023-05-18 06:01 UTC, Johnson-zs approved these changes, later dismissed

2023-05-18 06:02 UTC, GongHeng2017 commented
/merge

2023-05-18 06:09 UTC, BLumia approved these changes

2023-05-18 06:28 UTC, GongHeng2017 commented
/merge

2023-05-18 06:57 UTC, GongHeng2017 commented
/merge

2023-05-18 06:58 UTC, merged