fix: [desktop] On desktop, click "win + d", the openwith dialog hide.
linuxdeepin/dde-file-manager pull request #995
Opened 2023-05-19 03:01 UTC by GongHeng2017

the openwith dialog should model diskplay like old. so let the openwith dialog model display.

Log: fix issues
Bug: https://pms.uniontech.com/bug-view-199389.html

2023-05-19 03:09 UTC, Clauszy requested changes

2023-05-19 03:09 UTC, Clauszy commented on src/plugins/common/dfmplugin-utils/openwith/openwitheventreceiver.cpp
> +            const QWidgetList &topWidgets = qApp->topLevelWidgets();
不要const &函数返回的临时变量

2023-05-19 06:11 UTC, Clauszy approved these changes

2023-05-19 06:12 UTC, GongHeng2017 commented on src/plugins/common/dfmplugin-utils/openwith/openwitheventreceiver.cpp
> +            const QWidgetList &topWidgets = qApp->topLevelWidgets();
done

2023-05-19 06:14 UTC, Kakueeen approved these changes

2023-05-19 06:16 UTC, GongHeng2017 commented
/merge

2023-05-22 06:46 UTC, GongHeng2017 commented
/merge

2023-05-22 07:04 UTC, GongHeng2017 commented
/merge

2023-05-22 07:04 UTC, merged